config/routes.rb
Rails.application.routes.draw do
  resources :poems ,only: [:index, :show, :update, :destroy, :edit, :new, :create]
  root 'poems#index'
end

app/models/poem.rb
class Poem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = Poem.new(poem_params)

    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
        format.json { render :show, status: :created, location: @poem }
      else
        format.html { render :new }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:title, :content, :auther)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day13</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poems/_form.html.erb
<%= form_for(@poem) do |f| %>
  <% if @poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% @poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :auther %><br>
    <%= f.text_field :auther %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<h1>Editing Poem</h1>

<%= render 'form' %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Poems</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Auther</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td><%= poem.title %></td>
        <td><%= poem.content %></td>
        <td><%= poem.auther %></td>
        <td><%= link_to 'Show', poem %></td>
        <td><%= link_to 'Edit', edit_poem_path(poem) %></td>
        <td><%= link_to 'Destroy', poem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poem', new_poem_path %>

app/views/poems/new.html.erb
<h1>New Poem</h1>

<%= render 'form' %>

<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poem.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @poem.content %>
</p>

<p>
  <strong>Auther:</strong>
  <%= @poem.auther %>
</p>

<%= link_to 'Edit', edit_poem_path %> |
<%= link_to 'Back', poems_path %>